// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/zhangqiuhong/study/share/federation-project/packages/umi-host-remote/node_modules/.pnpm/@umijs+renderer-react@4.0.86_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type {  History } from '/Users/zhangqiuhong/study/share/federation-project/packages/umi-host-remote/node_modules/.pnpm/@umijs+renderer-react@4.0.86_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/zhangqiuhong/study/share/federation-project/packages/umi-host-remote/node_modules/.pnpm/umi@4.0.86_@babel+core@7.24.9_eslint@8.35.0_postcss@8.4.39_prettier@3.3.3_react-dom@18.3.1_re_ezcqfraqanko3fpbgsgo3mo6ju/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export const useServerInsertedHTML: Function = () => {};
// plugins
// plugins types.d.ts
