// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"safe-remote-component":{"path":"safe-remote-component","id":"safe-remote-component"},"register-then-import":{"path":"register-then-import","id":"register-then-import"},"no-exists-remote":{"path":"no-exists-remote","id":"no-exists-remote"},"raw-mf-component":{"path":"raw-mf-component","id":"raw-mf-component"},"dynamic-import":{"path":"dynamic-import","id":"dynamic-import"},"raw-mf-import":{"path":"raw-mf-import","id":"raw-mf-import"},"safe-import":{"path":"safe-import","id":"safe-import"},"bad-remote":{"path":"bad-remote","id":"bad-remote"}} as const;
  return {
    routes,
    routeComponents: {
'safe-remote-component': React.lazy(() => import(/* webpackChunkName: "src__pages__safe-remote-component" */'../../../src/pages/safe-remote-component.tsx')),
'register-then-import': React.lazy(() => import(/* webpackChunkName: "src__pages__register-then-import" */'../../../src/pages/register-then-import.tsx')),
'no-exists-remote': React.lazy(() => import(/* webpackChunkName: "src__pages__no-exists-remote" */'../../../src/pages/no-exists-remote.tsx')),
'raw-mf-component': React.lazy(() => import(/* webpackChunkName: "src__pages__raw-mf-component" */'../../../src/pages/raw-mf-component.tsx')),
'dynamic-import': React.lazy(() => import(/* webpackChunkName: "src__pages__dynamic-import" */'../../../src/pages/dynamic-import.tsx')),
'raw-mf-import': React.lazy(() => import(/* webpackChunkName: "src__pages__raw-mf-import" */'../../../src/pages/raw-mf-import.tsx')),
'safe-import': React.lazy(() => import(/* webpackChunkName: "src__pages__safe-import" */'../../../src/pages/safe-import.tsx')),
'bad-remote': React.lazy(() => import(/* webpackChunkName: "src__pages__bad-remote" */'../../../src/pages/bad-remote.tsx')),
},
  };
}
