// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
const umiExports = await import('/Users/zhangqiuhong/study/share/federation-project/packages/umi-host-remote/mf-host/src/.umi-production/umi.ts')
export const bootstrap = umiExports.bootstrap
export const mount = umiExports.mount
export const unmount = umiExports.unmount
export const update = umiExports.update
export default 1
